services:
  - type: web
    name: synth-mcp
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SYNTH_API_KEY
        sync: false